# Generated by Django 2.1.1 on 2018-11-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Racer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('ama_num', models.IntegerField()),
                ('district_num', models.CharField(max_length=5)),
                ('address', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=12)),
                ('zip_code', models.IntegerField(max_length=5)),
                ('date_joined', models.DateTimeField(verbose_name='date joined')),
            ],
        ),
    ]
