# Generated by Django 2.1.1 on 2018-11-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racer',
            name='zip_code',
            field=models.IntegerField(),
        ),
    ]
