# Generated by Django 2.1.1 on 2018-11-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racer', '0003_sponsors'),
    ]

    operations = [
        migrations.AddField(
            model_name='racer',
            name='instragram',
            field=models.CharField(default='bblack124l', max_length=20),
            preserve_default=False,
        ),
    ]
