# Generated by Django 2.1.1 on 2018-11-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racer', '0004_racer_instragram'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsors',
            name='sponsor_img',
            field=models.URLField(default='http://www.clubmoto.com/wp-content/uploads/2017/09/Club_Moto_300.png'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsors',
            name='sponsor_url',
            field=models.URLField(default='http://www.clubmoto.com/wp-content/uploads/2017/09/Club_Moto_300.png'),
            preserve_default=False,
        ),
    ]
