# Generated by Django 2.1.1 on 2018-12-21 04:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('racer', '0005_auto_20181121_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='racer',
            name='facebook',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='racer',
            name='linkedin',
            field=models.CharField(default='www.linkedin.com/bblackifyme', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='racer',
            name='phone',
            field=models.CharField(default='4083149647', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='racer',
            name='twitter',
            field=models.CharField(default='none', max_length=20),
            preserve_default=False,
        ),
    ]
