# Generated by Django 2.1.1 on 2018-12-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(max_length=25)),
                ('rescheduled', models.BooleanField()),
                ('points', models.BooleanField()),
                ('flier_url', models.URLField()),
                ('event', models.ForeignKey(on_delete='CASCADE', to='races.Event')),
            ],
        ),
    ]
